studentmanagement/main/urls.py
from django.urls import path
from main import views
urlpatterns = [
    path('',views.Index.as_view()),
    path('college/<int:pk>', views.CollegeDetail.as_view(), name = 'college'),
    path('college/', views.CollegeList.as_view()),
    path('create_college/', views.CollegeCreate.as_view()),
    path('update_college/<int:pk>', views.CollegeUpdate.as_view()),
    path('student_create/', views.StudentCreate.as_view()),
    path('delete_college/<int:pk>', views.StudentDelete.as_view())
]

studentmanagement/studentmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

studentmanagement/main/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name =  models.CharField(max_length = 256)
    roll_number = models.IntegerField(unique = True)
    college = models.ForeignKey('College', on_delete = models.CASCADE)
    
    def __str__(self):
        return self.name

class College(models.Model):
    name = models.CharField(max_length =256)

    def __str__(self):
        return self.name
            
            

studentmanagement/main/views.py
from django.http import HttpResponse

from django.shortcuts import render
from django.views import View
from django.views.generic import (
   DetailView,
   ListView,
   UpdateView,
   DeleteView,
   CreateView
 )
# Create your views here.
from main import models

class  Index(View):
    def get(self, request):
        return HttpResponse("GEt request")
    def post(self, request):
        return HttpResponse("POST request")

class CollegeDetail(DetailView):
    model = models.College
    template_name = 'college_detail.html'

# 5 generic views 1. Detail_view 2. list view 3. Create view 4. Update view 5.DELETE VIEW

class CollegeList(ListView):
    model = models.College
    template_name = 'college_list.html'
    context_object_name = 'colleges'

class CollegeCreate(CreateView):
    model = models.College
    template_name = 'college_create.html'
    fields = '__all__'
    success_url = '/college'
class CollegeUpdate(UpdateView):
    model = models.College
    template_name = 'college_create.html'
    fields = '__all__'
    success_url = '/college'


class StudentCreate(CreateView):
    model = models.Student
    template_name = 'student_create.html'
    fields = '__all__'
    success_url = '/'

class StudentDelete(DeleteView):
    model = models.Student
    template_name = 'confirm.html'
    fields = '__all__'
    success_url = '/'

studentmanagement/templates/college_create.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1> Add (++) Colleges </h1>
    <form action=" " method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">SUBMIT</button>
    </form>

</body>
</html>

studentmanagement/templates/college_detail.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title> college </title>
</head>
<body>
    <h1> College </h1>
    Name: {{ object.name }} <br />
    Students:
    <ul>
        {% for student in object.student_set.all %}
          <li> {{ student.name }} </li>
        {% endfor %}
    </ul>
</body>
</html>

studentmanagement/templates/college_list.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1> Colleges </h1>
    <ul>

        {% for college in colleges %}
        <li>
            <a href="{% url 'college' college.pk %}"> {{ college.name }} </a> 
        </li>
        {% endfor %}
     </ul>
</body>
</html>

studentmanagement/templates/confirm.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <form actiom="" method="POST">
        {% csrf_token %}
        <label for=""> Are You Want to Delete ? </label>
        <button> No </button>
        <button type="SUBMIT"> YES </button>
    </form>

</body>
</html>

studentmanagement/templates/student_create.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1> Add Students </h1>
    <form action=" " method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">SUBMIT</button>
    </form>

</body>
</html>